FROM node:11-alpine

RUN apk add build-base python
RUN mkdir -p /var/app/build /var/app/src
VOLUME /var/app/build
VOLUME /var/app/src
WORKDIR /var/app
COPY package.json /var/app
RUN npm i --build-from-source
COPY .babelrc /var/app
COPY config /var/app/config
COPY public /var/app/public
CMD ["npm", "run", "build"]